name: uchkisch
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.2.8
  screen_retriever: ^0.1.4
  hotkey_manager: ^0.1.7
  path_provider: ^2.0.11
  get: ^4.6.5
  plist_parser: '^0.0.9'
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
